### PR TITLE
Allow more than one harvested file and files differing by extension

### PR DESCRIPTION
**Pull request by paulomorgado**

### CODE REVIEW

**Comment by rseanhall** [comment]
Thanks. Please create an [issue](https://github.com/wixtoolset/issues/issues) to track this new functionality. Please add a test.

**Comment by paulomorgado** [comment]
Solves https://github.com/wixtoolset/issues/issues/6178

**Comment by paulomorgado** [comment]
@rseanhall, can you point me to the `HarvestFile` target tests?

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/Tools/blob/2480d0ad4bf4f0dd841697d6d607bb35a0fd8161/src/test/WixToolsetTest.BuildTasks/MsbuildHeatFixture.cs

**Comment by paulomorgado** [comment]
@rseanhall,

Added a unit test for the change. With out the change, the test fails.

Dropped the change from `File="@(HarvestFile)"` to `File="%(HarvestFile.FullPath)"` because it was due to the fact that I wasn't defining the `ComponentGroupName`.

Something like this is still failing:

    <HarvestFile Include="MyProgram.*">
      <ComponentGroupName>ProductComponents</ComponentGroupName>
      <DirectoryRefId>INSTALLFOLDER</DirectoryRefId>
      <SuppressRootDirectory>true</SuppressRootDirectory>
    </HarvestFile>

Is there a way to support this schenario?

**Comment by rseanhall** [comment]
MSBuild calls `Include="MyProgram.*"` globbing. I always forget the details of these things and have to look them up. It might be possible to use the `Identity` from HarvestFile and replace path separators with underscores.

I'm going to need all tests passing to accept this.

**Comment by paulomorgado** [comment]
The problem with glogging is that this:

```
<HarvestFile Include="MyProgram.*">
  <ComponentGroupName>ProductComponents</ComponentGroupName>
  <DirectoryRefId>INSTALLFOLDER</DirectoryRefId>
  <SuppressRootDirectory>true</SuppressRootDirectory>
</HarvestFile>
```

Will generate one .wsx file for each source file with a `ComponentGroup` declaration in each one.

Any guidance for these scenarios?

**Comment by rseanhall** [comment]
`HarvestFile` is just a wrapper around `heat.exe file`. I feel like that is a separate feature request asking for Heat to be able to take a wildcard in `heat.exe file`.

**Comment by barnson** [comment]
The primary motivation for `heat file` is to harvest one file's COM (etc.) registration.

**Comment by paulomorgado** [comment]
@rseanhall, test fixed. Sorry about that.

@barnson, I ended up having to copy everything to a new directory and harvesting the directory instead.

**Comment by rseanhall** [comment]
Thanks!

**Pull request merged**
